// main.js
console.log("main.js 已載入！準備翻譯...");
document.addEventListener("DOMContentLoaded", function () {
    // === 粒子背景 ===
    particlesJS("particles-js", {
        particles: {
            number: { value: 120 },
            color: { value: "#00e0ff" },
            shape: { type: "circle" },
            opacity: { value: 0.6, random: true },
            size: { value: 4, random: true },
            line_linked: { enable: true, distance: 150, color: "#00e0ff", opacity: 0.3, width: 1 },
            move: { enable: true, speed: 2 }
        },
        interactivity: {
            events: { onhover: { enable: true, mode: "repulse" } }
        }
    });

    // === 語言切換===
    const i18n = {
        'zh-TW': {
            // 導航欄
            'nav_challenges': '產業痛點',
            'nav_ai_advisor': 'AI 工程師',
            'nav_service': '服務項目',
            'nav_industry': '產業應用',
            'nav_about': '關於我們',
            'nav_contact': '聯絡我們',
            // AI顧問相關
            'ai_advisor_title': '專屬的製程AI工程師',
            'ai_advisor_subtitle': '輕鬆與現有設備無縫接軌,為您帶來三大核心價值',
            'ai_advisor_desc': '結合人工智慧與產業經驗,提供即時分析、預測與決策建議,協助企業提升效率與競爭力。',
            'ai_advisor_feature1': '24 小時智能諮詢,隨時解答您的問題',
            'ai_advisor_feature2': '根據數據自動生成最佳解決方案',
            'ai_advisor_feature3': '持續學習,隨企業成長優化建議',
            'ai_advisor_opt_title': '生產效率的自動優化師',
            'ai_advisor_opt_desc1': '就像一位不知疲倦、且永不犯錯的優化師傅。即時分析設備、環境以及歷史批次的數百個參數,透過多目標演算法自動在「最高良率」、「最低成本」與「最短製程時間」之間找到最佳平衡點。',
            'ai_advisor_opt_desc2': '您不再需要靠經驗反覆試錯,就能快速穩定生產,將良率與效率發揮到極致。',
            'ai_advisor_opt_value1': '40%↓',
            'ai_advisor_opt_label1': '調適時間',
            'ai_advisor_opt_value2': '15%↓',
            'ai_advisor_opt_label2': '調適成本',
            'ai_advisor_opt_value3': '10%↑',
            'ai_advisor_opt_label3': '產品良率',
            'ai_advisor_qc_title': '品質與成本的智慧管家',
            'ai_advisor_qc_desc1': '實現預防性品質控制,24小時監控生產狀況。一旦發現參數異常波動,會在問題發生前發出預警,讓您在品質問題產生之前就介入處理。',
            'ai_advisor_qc_desc2': '精準控制鍍膜厚度與原料配比,將每單位原料的效益最大化,確保營運成本始終處於最佳狀態。',
            'ai_advisor_qc_value1': '40%↓',
            'ai_advisor_qc_label1': '分析時間',
            'ai_advisor_qc_value2': '20%↓',
            'ai_advisor_qc_label2': '原料耗損',
            'ai_advisor_qc_value3': '10%↓',
            'ai_advisor_qc_label3': '不良率',
            'ai_advisor_know_title': '知識傳承與管理的智慧助理',
            'ai_advisor_know_desc1': '將資深師傅的寶貴經驗進行數位化，永久保存。我們透過先進的智慧整合技術，將所有分散的維修筆記、設備異常紀錄、標準作業流程（SOP）文件，甚至日常的溝通記錄等隱性知識，集中整理成一套全面且易於檢索的知識庫。',
            'ai_advisor_know_desc2': '以自然語言對話方式,隨時調用公司累積的智慧。無論新進人員請教還是管理者查詢,都能瞬間獲得最相關、最準確的資訊。',
            'ai_advisor_know_value1': '40%↓',
            'ai_advisor_know_label1': '培訓時間',
            'ai_advisor_know_value2': '40%↓',
            'ai_advisor_know_label2': '操作錯誤',
            'ai_advisor_know_value3': '40%↓',
            'ai_advisor_know_label3': '操作錯誤',
            'coating_challenges_title': '生產製造都會面臨的挑戰',
            'coating_challenges_subtitle': '這些痛點不僅直接影響生產效率,更蠶食著您的利潤空間',
            'coating_challenges_note': '面對上述挑戰,數位化與智慧化是提升鍍膜製程競爭力的關鍵。',
            'home': '首頁',
            'about': '關於我們',
            'service': '服務項目',
            'industry_applications': '產業應用', // 新增
            'contact': '聯絡我們',
            'company_title': '夆泩數位發展',
            'company_slogan': '專業、創新、信賴的夥伴',
            'about_content': '夆泩數位發展(ForeSense Tech)專注於數位創新與企業成長,結合專業顧問、技術研發與客製化解決方案,協助客戶在數位時代中脫穎而出。',
            'about_point1_title': '專業顧問團隊',
            'about_point1': '我們擁有經驗豐富的顧問團隊,深入了解各產業特性與市場趨勢,為每位客戶量身打造最適合的數位轉型策略,確保方案契合企業需求與發展目標。',
            'about_point2_title': '跨領域技術整合',
            'about_point2': '結合 AI、數據分析、雲端技術與軟體開發等多元專業,我們提供全方位的技術整合服務,幫助企業提升營運效率、優化決策流程,在競爭激烈的市場中保持領先地位。',
            'about_point3_title': '持續創新,追求卓越',
            'about_point3': '我們的成員來自 U-start 創新創業計畫「RAGtimAIze」團隊與 NYCU 創新創業競賽「好理加太」團隊,擁有豐富的創新實戰經驗。我們秉持著創業家精神,不斷探索新技術、開發創新解決方案,與客戶共同成長,追求卓越表現。',
            'coating_challenges_item_yield': '不穩定的產品良率',
            'coating_challenges_item_yield_desc': '產品品質波動大,良率難以控制,導致客戶抱怨與退貨',
            'coating_challenges_item_equip': '突發的設備故障',
            'coating_challenges_item_equip_desc': '設備突然故障造成停機,影響交期並增加維修成本',
            'coating_challenges_item_cost': '持續攀升的營運成本',
            'coating_challenges_item_cost_desc': '原料浪費嚴重,能源效率低下,成本控制困難',
            'coating_challenges_item_expert': '老師傅的經驗斷層',
            'coating_challenges_item_expert_desc': '寶貴的製程經驗無法有效傳承,新人培訓週期長',
            'service1': 'AI演算法應用',
            'service1_desc': '透過先進的機器學習技術，我們為製造業量身打造智慧演算法解決方案。從生產參數優化、良率預測到設備異常偵測，AI演算法能夠從海量數據中學習最佳實踐經驗，自動找出最優化的製程參數組合。',
            'service2': 'AI Agent建置',
            'service2_desc': '打造企業專屬的智能助理系統，24小時不間斷地協助員工處理日常任務。我們的AI Agent能夠理解自然語言指令，自動執行數據查詢、報告生成、異常通知等重複性工作。透過整合企業內部知識庫與作業流程，AI Agent不僅能即時回答技術問題，更能主動提供操作建議，將資深師傅的寶貴經驗數位化，讓新手也能快速上手複雜製程，有效解決技術傳承斷層問題。',
            'service3': 'AI 自動作業系統',
            'service3_desc': '建構端到端的智慧化生產管理平台，實現從原料投入到成品產出的全流程自動化控制。系統整合IoT感測器、生產設備、品管儀器等多元數據源，透過AI即時分析製程狀態，自動調整參數設定，確保產品品質穩定一致。當偵測到異常徵兆時，系統會提前預警並自動啟動應變機制，大幅降低人為錯誤與停機風險，讓您的工廠真正實現智慧製造轉型。',
            'contact_content': '歡迎透過電子郵件或電話與我們聯繫。',
            'about_point1_value1': '15+',
            'about_point1_label1': '年半導體產業經驗',
            'about_point1_value2': '10+',
            'about_point1_label2': '年鍍膜產業經驗',
            'about_point2_value1': '5+',
            'about_point2_label1': '核心技術領域',
            'about_point2_value2': '30%',
            'about_point2_label2': '平均效率提升',
            'about_point3_value1': '2',
            'about_point3_label1': '創業競賽獲獎',
            'about_point3_value2': '100%',
            'about_point3_label2': '創新精神',
            'address_label': '地址:',
            'address': '新竹縣竹北市光明一路349號',
            'phone_label': '電話:',
            'phone': '0921-353124、0911-843839',
            'email_label': 'Email:',
            'email': 'foresense0729@gmail.com',
            'service_time_label': '服務時間:',
            'service_time': '週一至週五 9:00-18:00',
            'footer': '版權所有 © 2025 夆泩數位發展',
            
            // 產業應用場景 (Industry Applications) 新增的鍵值對
            'industry_applications_title': '深入各產業的智慧製程解決方案',
            'industry_applications_subtitle': '從半導體到光學鍍膜，ForeSense AI 助力不同產業突破製程瓶頸',
            'ia_challenges_title': '面臨的挑戰',
            'ia_solution_title': 'ForeSense 解決方案',
            'ia_benefit_title': '實際效益',
            'ia_semi_title': '半導體製造',
            'ia_semi_overview_title': '產業概況',
            'ia_semi_overview': '半導體製程中的薄膜沉積是關鍵步驟，直接影響晶片效能與良率。面對先進製程節點的挑戰，製程參數的精準控制至關重要。',
            'ia_semi_challenge1': '良率波動難預測：製程參數微小變化導致良率大幅下降，傳統經驗法則難以應對 7nm 以下製程的複雜性',
            'ia_semi_challenge2': '設備維護成本高：Chamber 清潔週期難以最佳化，過度維護浪費資源，維護不足影響產品品質',
            'ia_semi_challenge3': '新製程開發週期長：新產品導入（NPI）需要大量實驗，耗時 3-6 個月才能穩定量產',
            'ia_semi_challenge4': '異常反應時間慢：發現製程異常時往往已產出大批不良品，損失慘重',
            'ia_semi_solution1': 'AI 預測良率模型：分析超過 200+ 製程參數，提前 24 小時預警良率異常，準確率達 92%',
            'ia_semi_solution2': '智慧設備保養排程：根據實際腔體狀況動態調整 PM（預防性維護）週期，延長設備壽命 15-20%',
            'ia_semi_solution3': '快速製程優化：透過 AI 建議最佳參數組合，將新製程開發時間縮短 40%',
            'ia_semi_solution4': '即時異常偵測：3-5 分鐘內發現製程偏移，立即發送警報並提供根因分析',
            'ia_semi_benefit1': '12-15%',
            'ia_semi_benefit1_label': '良率提升',
            'ia_semi_benefit2': '8-10%',
            'ia_semi_benefit2_label': '設備稼動率提升',
            'ia_semi_benefit3': '40%',
            'ia_semi_benefit3_label': 'NPI 時間縮短',
            'ia_semi_benefit4': '減少報廢成本：年節省 2,000-5,000 萬元',
            'ia_optic_title': '光學鍍膜',
            'ia_optic_overview': '光學鍍膜應用於相機鏡頭、AR/VR 顯示器、汽車抬頭顯示器等領域，對膜層厚度、均勻度要求極高。',
            'ia_optic_challenge1': '膜厚控制精度要求高：奈米級的膜厚偏差會影響光學性能，傳統監控方式反應不及時',
            'ia_optic_challenge2': '多層膜製程複雜：抗反射膜、濾光片等需要 10-30 層鍍膜，任一層失敗導致整批報廢',
            'ia_optic_challenge3': '色差與均勻度問題：大面積鍍膜時，邊緣與中心的膜厚差異難以控制',
            'ia_optic_challenge4': '客製化需求多：不同客戶規格差異大，製程參數調整依賴資深工程師經驗',
            'ia_optic_solution1': '即時膜厚監控與預測：整合光學監控系統（OMS）數據，AI 即時預測最終膜厚，提前 10-15 秒調整鍍率',
            'ia_optic_solution2': '多層膜智慧排程：自動計算每層最佳參數，減少人為設定錯誤，成功率提升至 98%',
            'ia_optic_solution3': '均勻度優化演算法：分析基板旋轉速度、靶材角度等參數，將膜厚均勻度提升 20%',
            'ia_optic_solution4': '知識庫快速調參：系統記錄所有成功製程參數，新規格產品可在 30 分鐘內找到相似配方',
            'ia_optic_benefit1': '15-18%',
            'ia_optic_benefit1_label': '良率提升',
            'ia_optic_benefit2': '20-25%',
            'ia_optic_benefit2_label': '膜厚一致性提升',
            'ia_optic_benefit3': '50%',
            'ia_optic_benefit3_label': '客製化產品交期縮短',
            'ia_optic_benefit4': '工程師調參時間節省：60%',
            'ia_tool_title': '工具機硬膜鍍膜',
            'ia_tool_overview': '刀具、模具的硬質鍍膜（如 TiN、TiAlN、DLC）決定其耐磨性與使用壽命。',
            'ia_tool_challenge1': '膜層附著力不穩定：批次間膜層容易剝落，客訴率高',
            'ia_tool_challenge2': '硬度與韌性難平衡：過硬容易脆裂，過軟耐磨性不足',
            'ia_tool_challenge3': '批量一致性差：同爐次不同位置的工件品質差異大',
            'ia_tool_challenge4': '製程黑盒子問題：業界依賴師傅經驗，技術難以傳承',
            'ia_tool_solution1': '附著力預警系統：監控離子轟擊能量、基材溫度，預測膜層結合強度',
            'ia_tool_solution2': '多目標參數優化：AI 平衡硬度（>2500HV）與韌性需求，找出最佳沉積條件',
            'ia_tool_solution3': '爐內均勻度控制：優化基材旋轉速度、氣體分佈，減少位置差異至 5% 以內',
            'ia_tool_solution4': '專家知識數位化：將老師傅經驗轉化為 AI 模型，新手也能調出高品質參數',
            'ia_tool_benefit1': '60%',
            'ia_tool_benefit1_label': '客訴率降低',
            'ia_tool_benefit2': '25-30%',
            'ia_tool_benefit2_label': '刀具壽命延長',
            'ia_tool_benefit3': '40%',
            'ia_tool_benefit3_label': '批次一致性提升',
            'ia_tool_benefit4': '新人培訓時間縮短：從 6 個月到 2 個月'
        },
        'en': {
            // Navigation Bar
            'nav_challenges': 'Industry Pain Points',
            'nav_ai_advisor': 'AI Engineer',
            'nav_service': 'Services',
            'nav_industry': 'Industry Applications',
            'nav_about': 'About Us',
            'nav_contact': 'Contact Us',
            // AI Advisor related
            'ai_advisor_title': 'Dedicated Process AI Engineer',
            'ai_advisor_subtitle': 'Seamlessly integrates with your existing equipment, bringing you three core values',
            'ai_advisor_desc': 'Combining artificial intelligence with industry experience, providing real-time analysis, prediction, and decision recommendations to help enterprises improve efficiency and competitiveness.',
            'ai_advisor_feature1': '24/7 intelligent consultation, answers your questions anytime',
            'ai_advisor_feature2': 'Automatically generates optimal solutions based on data',
            'ai_advisor_feature3': 'Continuous learning, advice optimized as your business grows',
            'ai_advisor_opt_title': 'Automatic Production Efficiency Optimizer',
            'ai_advisor_opt_desc1': 'Like a tireless and infallible optimizer. Instantly analyzes hundreds of parameters from equipment, environment, and historical batches, and uses multi-objective algorithms to automatically find the best balance between "highest yield", "lowest cost", and "shortest process time".',
            'ai_advisor_opt_desc2': 'No more trial and error by experience. You can quickly and stably produce, maximizing yield and efficiency.',
            'ai_advisor_opt_value1': '40%↓',
            'ai_advisor_opt_label1': 'Tuning Time',
            'ai_advisor_opt_value2': '15%↓',
            'ai_advisor_opt_label2': 'Adjustment Cost',
            'ai_advisor_opt_value3': '10%↑',
            'ai_advisor_opt_label3': 'Product Yield',
            'ai_advisor_qc_title': 'Smart Manager of Quality & Cost',
            'ai_advisor_qc_desc1': 'Implement predictive quality control with 24/7 production monitoring. Upon detecting anomalous parameter fluctuations, the system issues an early warning before the issue occurs, allowing you to intervene and address potential quality problems before they arise.',
            'ai_advisor_qc_desc2': 'Precisely control coating thickness and material ratios to maximize the benefit of each unit of material, ensuring operating costs are always optimal.',
            'ai_advisor_qc_value1': '10%',
            'ai_advisor_qc_label1': 'Analysis Time',
            'ai_advisor_qc_value2': '20%↓',
            'ai_advisor_qc_label2': 'Material Wastage',
            'ai_advisor_qc_value3': '10%↓',
            'ai_advisor_qc_label3': 'Defect Rate',
            'ai_advisor_know_title': 'Smart Assistant for Knowledge Management & Transfer',
            'ai_advisor_know_desc1': 'Digitally capture and permanently preserve the valuable expertise of senior technicians/masters.By leveraging advanced smart integration technology, we centralize and organize all scattered knowledge—including maintenance notes, equipment anomaly records, Standard Operating Procedures (SOPs), and even daily communication logs—into a comprehensive and easily retrievable knowledge base.',
            'ai_advisor_know_desc2': 'Access accumulated company wisdom via natural language dialogue. Whether new staff ask or managers query, you can instantly get the most relevant and accurate information.',
            'ai_advisor_know_value1': '40%↓',
            'ai_advisor_know_label1': 'Training Period',
            'ai_advisor_know_value2': '40%↓',
            'ai_advisor_know_label2': 'Operator Error',
            'ai_advisor_know_value3': '40%↓',
            'ai_advisor_know_label3': 'Report Writing Time',
            'coating_challenges_title': 'Challenges in the Manufacturing Sector',
            'coating_challenges_subtitle': 'These pain points not only directly affect production efficiency, but also erode your profit margin.',
            'coating_challenges_item_equip': 'Unexpected Equipment Failure',
            'coating_challenges_item_equip_desc': 'Sudden equipment failures cause downtime, affecting delivery schedules and increasing maintenance costs',
            'coating_challenges_item_cost': 'Rising Operating Costs',
            'coating_challenges_item_cost_desc': 'Severe material waste, low energy efficiency, difficult cost control',
            'coating_challenges_item_expert': 'Knowledge Transfer Gap from Senior Experts',
            'coating_challenges_item_expert_desc': 'Valuable process experience cannot be effectively passed on, leading to long training cycles for new employees',
            'coating_challenges_note': 'Facing these challenges, digitalization and intelligence are the keys to enhancing the competitiveness of coating processes.',
            'home': 'Home',
            'about': 'About Us',
            'service': 'Services',
            'industry_applications': 'Industry Applications', // 新增
            'contact': 'Contact Us',
            'company_title': 'ForeSense Tech',
            'company_slogan': 'Professional, Innovative, Trusted Partner',
            'about_content': 'ForeSense Tech focuses on digital innovation and business growth, combining professional consulting, technology development, and customized solutions to help clients stand out in the digital era.',
            'about_point1_title': 'Professional Consulting Team',
            'about_point1': 'We have experienced consultants who deeply understand industry trends and create customized digital transformation strategies that align with each client\'s needs and development goals.',
            'about_point2_title': 'Cross-Domain Technology Integration',
            'about_point2': 'Combining AI, data analytics, cloud technology, and software development, we provide comprehensive solutions that improve operational efficiency and optimize decision-making processes, keeping enterprises ahead in competitive markets.',
            'about_point3_title': 'Continuous Innovation, Pursuit of Excellence',
            'about_point3': 'Our team members from U-start "RAGtimAIze" and NYCU "好理加太" bring rich innovation experience. We embrace an entrepreneurial spirit, continuously exploring new technologies and developing innovative solutions alongside our clients, pursuing excellence.',
            'coating_challenges_item_yield': 'Inconsistent Product Yield',
            'coating_challenges_item_yield_desc': 'Significant product quality fluctuations, difficult yield control, leading to customer complaints and returns',
            'service1': 'Application of AI Algorithms',
            'service1_desc': 'Leveraging advanced Machine Learning technology, we tailor intelligent algorithmic solutions specifically for the manufacturing sector. Spanning applications from production parameter optimization and yield prediction to equipment anomaly detection, our AI algorithms learn best practices from massive datasets, automatically pinpointing the optimal combination of process parameters.',
            'service2': 'AI Agent Implementation',
            'service2_desc': 'A custom enterprise AI Assistant (AI Agent) provides 24/7 intelligent support, automating repetitive tasks like data querying and report generation. By integrating the digitized expertise of senior masters, the AI Agent can instantly answer technical questions and proactively offer operational advice, effectively shortening the learning curve for new staff and bridging the technical knowledge transfer gap.',
            'service3': 'System Integration',
            'service3_desc': 'We construct an end-to-end intelligent production management platform that achieves full-process automated control. By integrating data from IoT sensors and production equipment, the system leverages AI for real-time process analysis, automatically adjusting parameters to ensure stable quality. Upon detecting early signs of anomalies, the platform issues an advance warning and automatically initiates contingency mechanisms, significantly minimizing human error and downtime risks to enable a true Smart Manufacturing transformation.',
            'contact_content': 'Feel free to contact us via email or phone.',
            'about_point1_value1': '15+',
            'about_point1_label1': 'Years of Semiconductor Industry Experience',
            'about_point1_value2': '10+',
            'about_point1_label2': 'Years of Coating Industry Experience',

            'about_point2_value1': '5+',
            'about_point2_label1': 'Core Tech Domains',
            'about_point2_value2': '30%',
            'about_point2_label2': 'Avg. Efficiency Boost',

            'about_point3_value1': '2',
            'about_point3_label1': 'Competition Awards',
            'about_point3_value2': '100%',
            'about_point3_label2': 'Innovation Spirit',
            'address_label': 'Address:',
            'address': '349 Guangming 1st Rd., Zhubei City, Hsinchu County',
            'phone_label': 'Phone:',
            'phone': '(+886)921-353124、(+886)911-843839',
            'email_label': 'Email:',
            'email': 'foresense0729@gmail.com',
            'service_time_label': 'Service Time:',
            'service_time': 'Mon-Fri 9:00-18:00',
            'footer': 'Copyright © 2025 ForeSense Tech',
            
            // 產業應用場景 (Industry Applications) 新增的鍵值對
            'industry_applications_title': 'Smart Process Solutions Across Industries',
            'industry_applications_subtitle': 'From Semiconductors to Optical Coating, ForeSense AI Helps Various Industries Overcome Process Bottlenecks',
            'ia_challenges_title': 'Challenges Faced',
            'ia_solution_title': 'ForeSense Solution',
            'ia_benefit_title': 'Actual Benefits',
            'ia_semi_title': 'Semiconductor Manufacturing',
            'ia_semi_overview_title': 'Industry Overview',
            'ia_semi_overview': 'Thin film deposition is a critical step in semiconductor processes, directly impacting chip performance and yield. Precise control of process parameters is essential for advanced nodes.',
            'ia_semi_challenge1': 'Unpredictable Yield Fluctuation: Minor parameter changes lead to significant yield drops; traditional experience struggles with sub-7nm process complexity.',
            'ia_semi_challenge2': 'High Equipment Maintenance Cost: Chamber cleaning cycles are hard to optimize; over-maintenance wastes resources, under-maintenance affects quality.',
            'ia_semi_challenge3': 'Long New Process Development Cycle: New Product Introduction (NPI) requires extensive experiments, taking 3-6 months to stabilize volume production.',
            'ia_semi_challenge4': 'Slow Anomaly Response Time: Anomalies are often detected after large batches of defective products are produced, resulting in significant losses.',
            'ia_semi_solution1': 'AI Predictive Yield Model: Analyzes 200+ process parameters, giving a 24-hour early warning for yield anomalies with 92% accuracy.',
            'ia_semi_solution2': 'Smart Equipment Maintenance Scheduling: Dynamically adjusts PM (Preventive Maintenance) cycles based on actual chamber status, extending equipment lifespan by 15-20%.',
            'ia_semi_solution3': 'Rapid Process Optimization: AI suggests optimal parameter combinations, shortening new process development time by 40%.',
            'ia_semi_solution4': 'Real-time Anomaly Detection: Detects process drift within 3-5 minutes, immediately alerts and provides root cause analysis.',
            'ia_semi_benefit1': '12-15%',
            'ia_semi_benefit1_label': 'Yield Improvement',
            'ia_semi_benefit2': '8-10%',
            'ia_semi_benefit2_label': 'Equipment Utilization Boost',
            'ia_semi_benefit3': '40%',
            'ia_semi_benefit3_label': 'NPI Time Reduction',
            'ia_semi_benefit4': 'Reduce Scrap Cost: Annual savings of NT$ 20-50 million.',
            'ia_optic_title': 'Optical Coating',
            'ia_optic_overview': 'Optical coating for camera lenses, AR/VR displays, and automotive HUDs requires extremely high precision in film thickness and uniformity.',
            'ia_optic_challenge1': 'High Film Thickness Control Precision: Nanometer-level deviation affects optical performance; traditional monitoring is not timely.',
            'ia_optic_challenge2': 'Complex Multi-Layer Process: Anti-reflection films and filters require 10-30 layers; failure in one layer leads to batch scrap.',
            'ia_optic_challenge3': 'Color Difference & Uniformity Issues: Difficult to control thickness variation between the center and edge of large-area coatings.',
            'ia_optic_challenge4': 'High Customization Needs: Diverse customer specifications; parameter adjustments rely on senior engineer experience.',
            'ia_optic_solution1': 'Real-time Thickness Monitoring & Prediction: Integrates Optical Monitoring System (OMS) data, AI instantly predicts final thickness, adjusting deposition rate 10-15 seconds in advance.',
            'ia_optic_solution2': 'Smart Multi-Layer Scheduling: Automatically calculates optimal parameters for each layer, reducing human error, success rate up to 98%.',
            'ia_optic_solution3': 'Uniformity Optimization Algorithm: Analyzes substrate rotation speed, target angle, etc., improving thickness uniformity by 20%.',
            'ia_optic_solution4': 'Knowledge Base for Quick Tuning: System records all successful process parameters; similar recipes for new specs found in 30 minutes.',
            'ia_optic_benefit1': '15-18%',
            'ia_optic_benefit1_label': 'Yield Improvement',
            'ia_optic_benefit2': '20-25%',
            'ia_optic_benefit2_label': 'Thickness Consistency Improvement',
            'ia_optic_benefit3': '50%',
            'ia_optic_benefit3_label': 'Custom Product Lead Time Shortened',
            'ia_optic_benefit4': 'Engineer Tuning Time Saved: 60%',
            'ia_tool_title': 'Hard Coating for Machine Tools',
            'ia_tool_overview': 'Hard coating (e.g., TiN, TiAlN, DLC) on tools and molds determines their wear resistance and lifespan.',
            'ia_tool_challenge1': 'Unstable Film Adhesion: Film peeling between batches is common, leading to high customer complaints.',
            'ia_tool_challenge2': 'Hardness-Toughness Balance is Difficult: Too hard leads to brittleness, too soft lacks sufficient wear resistance.',
            'ia_tool_challenge3': 'Poor Batch Consistency: Quality variation in workpieces at different positions within the same batch.',
            'ia_tool_challenge4': 'Process Black Box Issue: Industry relies on master technicians\' experience; technology transfer is difficult.',
            'ia_tool_solution1': 'Adhesion Early Warning System: Monitors ion bombardment energy and substrate temperature to predict film bonding strength.',
            'ia_tool_solution2': 'Multi-Objective Parameter Optimization: AI balances hardness (>2500HV) and toughness needs to find optimal deposition conditions.',
            'ia_tool_solution3': 'In-Furnace Uniformity Control: Optimizes substrate rotation speed and gas distribution, reducing positional variation to < 5%.',
            'ia_tool_solution4': 'Expert Knowledge Digitalization: Transforms master technicians\' experience into an AI model, allowing novices to achieve high-quality parameters.',
            'ia_tool_benefit1': '60%',
            'ia_tool_benefit1_label': 'Customer Complaint Reduction',
            'ia_tool_benefit2': '25-30%',
            'ia_tool_benefit2_label': 'Tool Lifespan Extension',
            'ia_tool_benefit3': '40%',
            'ia_tool_benefit3_label': 'Batch Consistency Improvement',
            'ia_tool_benefit4': 'New Staff Training Time Shortened: From 6 months to 2 months'
        }
    };

    // 翻譯函數（超穩版）
    function translate(lang) {
        document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (i18n[lang] && i18n[lang][key] !== undefined) {
            el.textContent = i18n[lang][key];
        }
        });
    }

    // 預設繁體中文
    translate('zh-TW');

    // 語言按鈕點擊
    document.querySelectorAll('.lang-switch').forEach(btn => {
        btn.addEventListener('click', function () {
        const lang = this.getAttribute('data-lang');
        translate(lang);

        // 可選：切換按鈕樣式
        document.querySelectorAll('.lang-switch').forEach(b => b.classList.remove('bg-cyan-500/30', 'border-cyan-400'));
        this.classList.add('bg-cyan-500/30', 'border-cyan-400');
        });
    });
});
